### ISSUE TITLE
Animations and responsiveness

### ISSUE THREAD

**Issue by denis-sokolov** [citrusbyte/react-drag-and-zoom#2]
The 1s animation duration results in a smooth animation, but in a slightly unresponsive feel. For UI elements that I operate directly on, I expect to have instant feedback. If I drag, zoom, resize something, I expect that to change its appearance instantly. For items that I _request to change_ (archive, hide, minimize), it’s okay to see some animation.

I feel like for this component the animation should have no duration. See [Google Maps](https://www.google.com/maps/) behavior for inspiration. Your opinion may vary, so feel free to disagree!

**Comment by nachoaIvarez** [comment]
The 1s animation is a necessity given the not-ideal zooming behavior you reported in #1. If smaller or non animation duration value is provided, the image jumps around. I will close this issue since is directly related to #1.
